"""empty message

Revision ID: 149a061160c5
Revises: c2939aca443c
Create Date: 2020-06-10 12:17:26.600281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149a061160c5'
down_revision = 'c2939aca443c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('contrasena', sa.String(length=20), nullable=False))
    op.add_column('usuario', sa.Column('foto', sa.String(length=20), nullable=False))
    op.drop_column('usuario', 'image_file')
    op.drop_column('usuario', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('password', sa.VARCHAR(length=20), nullable=False))
    op.add_column('usuario', sa.Column('image_file', sa.VARCHAR(length=20), nullable=False))
    op.drop_column('usuario', 'foto')
    op.drop_column('usuario', 'contrasena')
    # ### end Alembic commands ###
