"""empty message

Revision ID: 1e38083cd18c
Revises: 
Create Date: 2020-06-09 13:30:12.313142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e38083cd18c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Usuario',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('mail', sa.String(length=100), nullable=False),
    sa.Column('contrasena', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=10), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('trabajo', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('mail'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Evento',
    sa.Column('eventID', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('siglas', sa.String(length=10), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=False),
    sa.Column('duracion', sa.Integer(), nullable=False),
    sa.Column('asistentes', sa.Integer(), nullable=False),
    sa.Column('fechahora', sa.DateTime(), nullable=False),
    sa.Column('costo', sa.Integer(), nullable=False),
    sa.Column('lugar', sa.String(length=100), nullable=False),
    sa.Column('imagen', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Integer(), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['Usuario.userID'], ),
    sa.PrimaryKeyConstraint('eventID')
    )
    op.create_table('Boleto',
    sa.Column('folio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('eventID', sa.Integer(), nullable=True),
    sa.Column('expedicion', sa.DateTime(), nullable=False),
    sa.Column('imagen', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['eventID'], ['Evento.eventID'], ),
    sa.ForeignKeyConstraint(['userID'], ['Usuario.userID'], ),
    sa.PrimaryKeyConstraint('folio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Boleto')
    op.drop_table('Evento')
    op.drop_table('Usuario')
    # ### end Alembic commands ###
