"""empty message

Revision ID: 3da94c284326
Revises: c22c48999711
Create Date: 2020-06-10 18:21:09.902358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da94c284326'
down_revision = 'c22c48999711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('mail', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.Column('contrasena', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=10), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('trabajo', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('mail'),
    sa.UniqueConstraint('username')
    )
    op.create_table('evento',
    sa.Column('eventID', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('siglas', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('duracion', sa.String(length=50), nullable=False),
    sa.Column('asistentes', sa.Integer(), nullable=False),
    sa.Column('costo', sa.Integer(), nullable=False),
    sa.Column('lugar', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('imagen', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.userID'], ),
    sa.PrimaryKeyConstraint('eventID')
    )
    op.create_table('boleto',
    sa.Column('folio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('eventID', sa.Integer(), nullable=True),
    sa.Column('Fecha', sa.DateTime(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('imagen', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['eventID'], ['evento.eventID'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.userID'], ),
    sa.PrimaryKeyConstraint('folio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boleto')
    op.drop_table('evento')
    op.drop_table('usuario')
    # ### end Alembic commands ###
