"""empty message

Revision ID: 47a28d6bbc35
Revises: 9360c76f21db
Create Date: 2020-06-10 09:17:09.766053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a28d6bbc35'
down_revision = '9360c76f21db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nombre', sa.String(length=150), nullable=True))
    op.add_column('user', sa.Column('telefono', sa.String(length=20), nullable=True))
    op.drop_column('user', 'numTelefono')
    op.drop_column('user', 'nombreCompleto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nombreCompleto', sa.VARCHAR(length=150), nullable=True))
    op.add_column('user', sa.Column('numTelefono', sa.VARCHAR(length=20), nullable=True))
    op.drop_column('user', 'telefono')
    op.drop_column('user', 'nombre')
    # ### end Alembic commands ###
