"""empty message

Revision ID: 480d73204f90
Revises: 86c59ac7485c
Create Date: 2020-06-08 20:34:06.436697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '480d73204f90'
down_revision = '86c59ac7485c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Boleto', sa.Column('eventID', sa.Integer(), nullable=True))
    op.add_column('Boleto', sa.Column('expedicion', sa.DateTime(), nullable=False))
    op.add_column('Boleto', sa.Column('folio', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('Boleto', sa.Column('userID', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'Boleto', type_='foreignkey')
    op.drop_constraint(None, 'Boleto', type_='foreignkey')
    op.create_foreign_key(None, 'Boleto', 'Usuario', ['userID'], ['userID'])
    op.create_foreign_key(None, 'Boleto', 'Evento', ['eventID'], ['eventID'])
    op.drop_column('Boleto', 'Expedicion')
    op.drop_column('Boleto', 'Folio')
    op.drop_column('Boleto', 'UserID')
    op.drop_column('Boleto', 'EventID')
    op.add_column('Evento', sa.Column('asistentes', sa.Integer(), nullable=False))
    op.add_column('Evento', sa.Column('costo', sa.Integer(), nullable=False))
    op.add_column('Evento', sa.Column('descripcion', sa.String(length=1000), nullable=False))
    op.add_column('Evento', sa.Column('duracion', sa.Integer(), nullable=False))
    op.add_column('Evento', sa.Column('eventID', sa.Integer(), nullable=False))
    op.add_column('Evento', sa.Column('fechahora', sa.DateTime(), nullable=False))
    op.add_column('Evento', sa.Column('lugar', sa.String(length=100), nullable=False))
    op.add_column('Evento', sa.Column('nombre', sa.String(length=50), nullable=False))
    op.add_column('Evento', sa.Column('siglas', sa.String(length=10), nullable=False))
    op.add_column('Evento', sa.Column('userID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Evento', 'Usuario', ['userID'], ['userID'])
    op.drop_column('Evento', 'Duracion')
    op.drop_column('Evento', 'Nombre')
    op.drop_column('Evento', 'Lugar')
    op.drop_column('Evento', 'Costo')
    op.drop_column('Evento', 'Siglas')
    op.drop_column('Evento', 'Descripcion')
    op.drop_column('Evento', 'EventID')
    op.drop_column('Evento', 'Hora')
    op.drop_column('Evento', 'Asistentes')
    op.drop_column('Evento', 'Fecha')
    op.add_column('Registra', sa.Column('eventID', sa.Integer(), nullable=True))
    op.add_column('Registra', sa.Column('registroID', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('Registra', sa.Column('userID', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'Registra', type_='foreignkey')
    op.drop_constraint(None, 'Registra', type_='foreignkey')
    op.create_foreign_key(None, 'Registra', 'Evento', ['eventID'], ['eventID'])
    op.create_foreign_key(None, 'Registra', 'Usuario', ['userID'], ['userID'])
    op.drop_column('Registra', 'RegistroID')
    op.drop_column('Registra', 'UserID')
    op.drop_column('Registra', 'EventID')
    op.add_column('Usuario', sa.Column('userID', sa.Integer(), nullable=False))
    op.add_column('Usuario', sa.Column('username', sa.String(length=30), nullable=False))
    op.create_unique_constraint(None, 'Usuario', ['username'])
    op.drop_column('Usuario', 'UserID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuario', sa.Column('UserID', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'Usuario', type_='unique')
    op.drop_column('Usuario', 'username')
    op.drop_column('Usuario', 'userID')
    op.add_column('Registra', sa.Column('EventID', sa.INTEGER(), nullable=True))
    op.add_column('Registra', sa.Column('UserID', sa.INTEGER(), nullable=True))
    op.add_column('Registra', sa.Column('RegistroID', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'Registra', type_='foreignkey')
    op.drop_constraint(None, 'Registra', type_='foreignkey')
    op.create_foreign_key(None, 'Registra', 'Evento', ['EventID'], ['EventID'])
    op.create_foreign_key(None, 'Registra', 'Usuario', ['UserID'], ['UserID'])
    op.drop_column('Registra', 'userID')
    op.drop_column('Registra', 'registroID')
    op.drop_column('Registra', 'eventID')
    op.add_column('Evento', sa.Column('Fecha', sa.DATETIME(), nullable=False))
    op.add_column('Evento', sa.Column('Asistentes', sa.INTEGER(), nullable=False))
    op.add_column('Evento', sa.Column('Hora', sa.DATETIME(), nullable=False))
    op.add_column('Evento', sa.Column('EventID', sa.INTEGER(), nullable=False))
    op.add_column('Evento', sa.Column('Descripcion', sa.VARCHAR(length=1000), nullable=False))
    op.add_column('Evento', sa.Column('Siglas', sa.VARCHAR(length=10), nullable=False))
    op.add_column('Evento', sa.Column('Costo', sa.INTEGER(), nullable=False))
    op.add_column('Evento', sa.Column('Lugar', sa.VARCHAR(length=100), nullable=False))
    op.add_column('Evento', sa.Column('Nombre', sa.VARCHAR(length=50), nullable=False))
    op.add_column('Evento', sa.Column('Duracion', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'Evento', type_='foreignkey')
    op.drop_column('Evento', 'userID')
    op.drop_column('Evento', 'siglas')
    op.drop_column('Evento', 'nombre')
    op.drop_column('Evento', 'lugar')
    op.drop_column('Evento', 'fechahora')
    op.drop_column('Evento', 'eventID')
    op.drop_column('Evento', 'duracion')
    op.drop_column('Evento', 'descripcion')
    op.drop_column('Evento', 'costo')
    op.drop_column('Evento', 'asistentes')
    op.add_column('Boleto', sa.Column('EventID', sa.INTEGER(), nullable=True))
    op.add_column('Boleto', sa.Column('UserID', sa.INTEGER(), nullable=True))
    op.add_column('Boleto', sa.Column('Folio', sa.INTEGER(), nullable=False))
    op.add_column('Boleto', sa.Column('Expedicion', sa.DATETIME(), nullable=False))
    op.drop_constraint(None, 'Boleto', type_='foreignkey')
    op.drop_constraint(None, 'Boleto', type_='foreignkey')
    op.create_foreign_key(None, 'Boleto', 'Evento', ['EventID'], ['EventID'])
    op.create_foreign_key(None, 'Boleto', 'Usuario', ['UserID'], ['UserID'])
    op.drop_column('Boleto', 'userID')
    op.drop_column('Boleto', 'folio')
    op.drop_column('Boleto', 'expedicion')
    op.drop_column('Boleto', 'eventID')
    # ### end Alembic commands ###
