"""empty message

Revision ID: 86c59ac7485c
Revises: 
Create Date: 2020-05-27 23:52:49.829688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86c59ac7485c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Evento',
    sa.Column('EventID', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=50), nullable=False),
    sa.Column('Siglas', sa.String(length=10), nullable=False),
    sa.Column('Descripcion', sa.String(length=1000), nullable=False),
    sa.Column('Duracion', sa.Integer(), nullable=False),
    sa.Column('Asistentes', sa.Integer(), nullable=False),
    sa.Column('Fecha', sa.DateTime(), nullable=False),
    sa.Column('Hora', sa.DateTime(), nullable=False),
    sa.Column('Costo', sa.Integer(), nullable=False),
    sa.Column('Lugar', sa.String(length=100), nullable=False),
    sa.Column('imagen', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('EventID')
    )
    op.create_table('Usuario',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('mail', sa.String(length=100), nullable=False),
    sa.Column('contrasena', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=10), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('trabajo', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('mail'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('Boleto',
    sa.Column('Folio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('EventID', sa.Integer(), nullable=True),
    sa.Column('Expedicion', sa.DateTime(), nullable=False),
    sa.Column('imagen', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['EventID'], ['Evento.EventID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['Usuario.UserID'], ),
    sa.PrimaryKeyConstraint('Folio')
    )
    op.create_table('Registra',
    sa.Column('RegistroID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('EventID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['EventID'], ['Evento.EventID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['Usuario.UserID'], ),
    sa.PrimaryKeyConstraint('RegistroID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Registra')
    op.drop_table('Boleto')
    op.drop_table('Usuario')
    op.drop_table('Evento')
    # ### end Alembic commands ###
