"""empty message

Revision ID: aedd01bc9108
Revises: c9b470e4a5d3
Create Date: 2020-06-10 09:46:38.947177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aedd01bc9108'
down_revision = 'c9b470e4a5d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=10), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('trabajo', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('user')
    op.drop_constraint(None, 'boleto', type_='foreignkey')
    op.create_foreign_key(None, 'boleto', 'usuario', ['user_id'], ['id'])
    op.drop_constraint(None, 'evento', type_='foreignkey')
    op.create_foreign_key(None, 'evento', 'usuario', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evento', type_='foreignkey')
    op.create_foreign_key(None, 'evento', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'boleto', type_='foreignkey')
    op.create_foreign_key(None, 'boleto', 'user', ['user_id'], ['id'])
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('image_file', sa.VARCHAR(length=20), nullable=False),
    sa.Column('password', sa.VARCHAR(length=60), nullable=False),
    sa.Column('numTelefono', sa.VARCHAR(length=20), nullable=True),
    sa.Column('edad', sa.INTEGER(), nullable=True),
    sa.Column('empresa', sa.VARCHAR(length=20), nullable=True),
    sa.Column('nombreCompleto', sa.VARCHAR(length=150), nullable=True),
    sa.Column('residencia', sa.VARCHAR(length=70), nullable=True),
    sa.Column('nombre', sa.VARCHAR(length=150), nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=20), nullable=True),
    sa.Column('estado', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('usuario')
    # ### end Alembic commands ###
