"""empty message

Revision ID: b6653c6db777
Revises: c4ea31034eeb
Create Date: 2020-06-10 13:33:55.806611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6653c6db777'
down_revision = 'c4ea31034eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'foto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('foto', sa.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
