"""empty message

Revision ID: c1ddc4e5ffad
Revises: 17c69f1da9da
Create Date: 2020-06-10 18:02:49.227263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1ddc4e5ffad'
down_revision = '17c69f1da9da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boleto', sa.Column('eventID', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'boleto', type_='foreignkey')
    op.create_foreign_key(None, 'boleto', 'evento', ['eventID'], ['eventID'])
    op.drop_column('boleto', 'idEvento')
    op.add_column('evento', sa.Column('eventID', sa.Integer(), nullable=False))
    op.drop_column('evento', 'idEvento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evento', sa.Column('idEvento', sa.INTEGER(), nullable=False))
    op.drop_column('evento', 'eventID')
    op.add_column('boleto', sa.Column('idEvento', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'boleto', type_='foreignkey')
    op.create_foreign_key(None, 'boleto', 'evento', ['idEvento'], ['idEvento'])
    op.drop_column('boleto', 'eventID')
    # ### end Alembic commands ###
