"""empty message

Revision ID: c9b470e4a5d3
Revises: 47a28d6bbc35
Create Date: 2020-06-10 09:26:52.489693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9b470e4a5d3'
down_revision = '47a28d6bbc35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('estado', sa.String(length=50), nullable=True))
    op.drop_column('user', 'residencia')
    op.drop_column('user', 'numTelefono')
    op.drop_column('user', 'nombreCompleto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nombreCompleto', sa.VARCHAR(length=150), nullable=True))
    op.add_column('user', sa.Column('numTelefono', sa.VARCHAR(length=20), nullable=True))
    op.add_column('user', sa.Column('residencia', sa.VARCHAR(length=70), nullable=True))
    op.drop_column('user', 'estado')
    # ### end Alembic commands ###
